# Generated by Claritty Platform
# Fullstack Python fastapi + vite
# Platform: linux/amd64 (AWS Fargate requirement)
#
# 🏗️ PLATFORM-CONTROLLED INFRASTRUCTURE:
# - ECR Public Gallery base images (no Docker Hub rate limits)
# - nginx.conf generated inline with /health endpoint (ALB-compatible)
# - Resilient npm install for frontend (handles lockfile issues)
# - supervisor manages nginx + Python processes
# - nginx (port 3200) proxies to Python backend (port 8000)

# ============================================================================
# Stage 1: Build Frontend
# ============================================================================
# ✅ Uses ECR Public Gallery instead of Docker Hub to avoid rate limiting
FROM --platform=linux/amd64 public.ecr.aws/docker/library/node:20-alpine AS frontend-builder

WORKDIR /app/frontend

# Copy frontend dependency files
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install --no-audit --no-fund --prefer-offline

# Copy frontend source code
COPY frontend/ ./

# Build frontend (outputs to dist/)
RUN npm run build

# ============================================================================
# Stage 2: Production - Python + Nginx + Supervisor
# ============================================================================
# ✅ Uses ECR Public Gallery instead of Docker Hub to avoid rate limiting
FROM --platform=linux/amd64 public.ecr.aws/docker/library/python:3.11-slim

WORKDIR /app

# Install system dependencies (nginx, supervisor, wget for health checks)
RUN apt-get update && apt-get install -y \
    gcc \
    nginx \
    supervisor \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy Python dependency files (from detected location, may be in subdirectory)
COPY backend/requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Python application code
COPY . .

# Copy built frontend from Stage 1
COPY --from=frontend-builder /app/frontend/dist /app/frontend/dist

# ============================================================================
# 🏗️ PLATFORM-GENERATED nginx.conf (NO manual configuration needed!)
# ============================================================================
# The platform generates nginx.conf inline with:
# 1. /health endpoint (required by ALB health checks) - returns 200 OK
# 2. Static asset serving (/assets/ from Vite build with 1-year cache)
# 3. Widget HTML serving (/widget serves widget.html)
# 4. API proxying (all other requests → Python backend on port 8000)
#
# Why inline generation?
# - No buildspec sed/awk injection needed (simpler, faster builds)
# - Health endpoint baked in (ALB-compatible out of the box)
# - Consistent across all deployments (no manual nginx config needed)
# - Developers don't need nginx knowledge (platform-controlled)
# ============================================================================
RUN echo 'user root;\n\
worker_processes auto;\n\
error_log /var/log/nginx/error.log warn;\n\
pid /var/run/nginx.pid;\n\
\n\
events {\n\
    worker_connections 1024;\n\
}\n\
\n\
http {\n\
    include /etc/nginx/mime.types;\n\
    default_type application/octet-stream;\n\
    sendfile on;\n\
    keepalive_timeout 65;\n\
    gzip on;\n\
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;\n\
\n\
    server {\n\
        listen 3200;\n\
        server_name _;\n\
        root /app/frontend/dist;\n\
        index index.html;\n\
\n\
        # Health check endpoint (required by ALB)\n\
        location /health {\n\
            return 200 "OK";\n\
            add_header Content-Type text/plain;\n\
        }\n\
\n\
        # Proxy API requests to Python backend\n\
        location /api/ {\n\
            proxy_pass http://127.0.0.1:8000;\n\
            proxy_http_version 1.1;\n\
            # NOTE: do NOT send "Connection: upgrade" on /api/. These headers\n\
            # were emitted unconditionally (the echo writes a literal\n\
            # "\$http_upgrade", so Upgrade was a constant non-empty string),\n\
            # which made uvicorn treat every POST as a connection upgrade and\n\
            # DROP the request body — FastAPI then returned 422 "Field required\n\
            # (body)". The app has no /api websockets, so plain proxying is right.\n\
            proxy_set_header Host \$host;\n\
            proxy_set_header X-Real-IP \$remote_addr;\n\
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n\
            proxy_set_header X-Forwarded-Proto \$scheme;\n\
        }\n\
\n\
        # Exact match for index.html (prevents redirect loop)\n\
        location = /index.html {\n\
            add_header Cache-Control "no-cache";\n\
        }\n\
        \n\
        # Serve frontend SPA (fallback to index.html for client-side routing)\n\
        location / {\n\
            try_files \$uri \$uri/ /index.html;\n\
        }\n\
\n\
        # Cache static assets (JS, CSS, images, fonts)\n\
        location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {\n\
            expires 1y;\n\
            add_header Cache-Control "public, immutable";\n\
        }\n\
    }\n\
}' > /etc/nginx/nginx.conf

# Generate supervisor configuration
RUN echo '[supervisord]\n\
nodaemon=true\n\
user=root\n\
\n\
[program:nginx]\n\
command=/usr/sbin/nginx -g "daemon off;"\n\
autostart=true\n\
autorestart=true\n\
stdout_logfile=/dev/stdout\n\
stdout_logfile_maxbytes=0\n\
stderr_logfile=/dev/stderr\n\
stderr_logfile_maxbytes=0\n\
\n\
[program:python]\n\
command=uvicorn backend.main:app --host 0.0.0.0 --port 8000\n\
directory=/app\n\
autostart=true\n\
autorestart=true\n\
stdout_logfile=/dev/stdout\n\
stdout_logfile_maxbytes=0\n\
stderr_logfile=/dev/stderr\n\
stderr_logfile_maxbytes=0' > /etc/supervisor/conf.d/supervisord.conf

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Expose port (nginx listens on 3200, Python on 8000 internally)
EXPOSE 3200

# Health check (nginx handles /health endpoint)
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3200/health || exit 1

# Start supervisor (runs both nginx and Python)
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
